
server:
  port : 8005
  tomcat:
    max-threads: 50

eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8000/eureka/ #服务注册到哪里去

spring:
  application:
    name : eureka-order-feign
  main:
    allow-bean-definition-overriding: true

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

