
server:
  port : 8003

eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8000/eureka/ #服务注册到哪里去

spring:
  application:
    name : eureka-zuul

zuul:
  routes:
    api-a:
      path: /api-user/**
      service-id: eureka-user
    api-b:
      path: /api-order/**
      service-id: eureka-order